services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: /run/secrets/typeorm_username
      POSTGRES_PASSWORD: /run/secrets/typeorm_password
      POSTGRES_DB: /run/secrets/typeorm_database
    secrets:
      - typeorm_password
      - typeorm_username
      - typeorm_database
    ports:
      - '5433:5432'
    volumes:
      - pgdata_production:/var/lib/postgresql/data
    networks:
      - app-net
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U /run/secrets/typeorm_username -d /run/secrets/typeorm_database',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure

  migrations:
    image: samg1008/products-workflow-api:latest
    command: sh -c "./wait-for-postgres.sh postgres 5432 60 && npx typeorm migration:run -d dist/data-source.js"
    environment:
      NODE_ENV: production
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: postgres
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: /run/secrets/typeorm_username
      TYPEORM_PASSWORD: /run/secrets/typeorm_password
      TYPEORM_DATABASE: /run/secrets/typeorm_database
      TYPEORM_MIGRATIONS: dist/migrations/*.js
      TYPEORM_ENTITIES: dist/**/*.entity.js
    secrets:
      - typeorm_username
      - typeorm_password
      - typeorm_database
    networks:
      - app-net
    depends_on:
      - postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints: [node.role == manager]

  api:
    image: samg1008/products-workflow-api:latest
    environment:
      NODE_ENV: production
      PORT: 8080
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: postgres
      TYPEORM_PORT: 5432
      TYPEORM_RUN_MIGRATIONS: 'true' # Activer les migrations en production
      TYPEORM_SYNCHRONIZE: 'false'
      TYPEORM_ENTITIES: dist/**/*.entity.js
      TYPEORM_MIGRATIONS: dist/migrations/*.js
      TYPEORM_MIGRATIONS_TABLE_NAME: custom_migration_table
      TYPEORM_USERNAME: /run/secrets/typeorm_username
      TYPEORM_PASSWORD: /run/secrets/typeorm_password
      TYPEORM_DATABASE: /run/secrets/typeorm_database
      TYPEORM_LOGGING: 'true'
    secrets:
      - typeorm_username
      - typeorm_password
      - typeorm_database
    ports:
      - '8080:8080'
    networks:
      - app-net
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M

secrets:
  typeorm_username:
    external: true
  typeorm_password:
    external: true
  typeorm_database:
    external: true

volumes:
  pgdata_production:

networks:
  app-net:
    driver: overlay
    attachable: true
