apiVersion: v1
kind: Secret
metadata:
  name: typeorm-secrets
  namespace: postgres
type: Opaque
stringData:
  TYPEORM_USERNAME: admin_postgres
  TYPEORM_PASSWORD: admin_postgres
  TYPEORM_DATABASE: products_db
